# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f612d442d26b8a06100826fa542e5e730535bd71b57ecdd00796c14e1a231fba6261b06185388bb55179ec8dea7d9f38ff1a1a357d65968f79a431a53ba0129

test:
  secret_key_base: 80f2da8ae28dc918330b97008f21f7b4b9daf1af2b91be9dce5e4a0b5eb5dfba9317ff208c54e4e185fec8e8475ac10cd4ce539445f92b81acfa9ce8c1d64a39

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
